### PR TITLE
[COOK-4673] Less greedy regex on checking rule

### PR DESCRIPTION
**Pull request by mwalton236**

### CODE REVIEW

**Comment by martinb3** [comment]
@mwalton236 Was this change required to fix a bug in behavior? Just curious about the need for it. I'd love to see a test go in with it.

**Comment by mwalton236** [comment]
Details should be on the opscode ticket

**Comment by mwalton236** [comment]
https://tickets.opscode.com/browse/COOK-4673

**Comment by martinb3** [comment]
Copied the info over into https://github.com/opscode-cookbooks/firewall/issues/32.

**Comment by mwalton236** [comment]
Thanks... I think. However why was this not taken from my pull request?

**Comment by martinb3** [comment]
Hi! Your code required a rebase. Since it was literally 4 characters, I just changed it.

**Pull request closed without merging**
