### PR TITLE
Allow ipv6 addresses in firewall_rule

### PR DESCRIPTION
**Pull request by tg90nor**
This regex is very ugly, but it gets the job done.

An alternative approach could be to require source and destination addresses to be of type IPAddr, which has built in validation, but it would probably break backwards compatibility quite bad, unless it is possible to automatically create an IPAddr object from a supplied string.

This is a possible fix to issue #43

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @tg90nor

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by tg90nor** [comment]
I tried doing the validation with callbacks instead of regex. It seems to work fine. I like this approach much better than the giant regex.

**Comment by martinb3** [comment]
Hey! Thanks for this! Do you think you could add a test to verify that after ipv6 rule is run, the appropriate rule is present in the firewall rules? If not, I'll try to get to that soon and merge this with it. Thanks again!

**Comment by tg90nor** [comment]
I have a unit test ready, and I am working on integration tests.

**Comment by tg90nor** [comment]
Seems the iptables provider need quite a bit of work. Ufw works fine. I have not tested firewalld yet.
I will return with more patches when they are ready.

**Comment by tg90nor** [comment]
Added IPv6 support in iptables and firewalld.

Some potential pitfalls i can think of:
* If a rule contains an ipv4 source address and ipv6 destination address, or vice versa, things will break
* The iptables and firewalld ip version detection code will not work on raw rules, resulting in the provisioner attempting to add the rule both for ipv4 and ipv6
* This change modifies behaviour of iptables and firewalld behaviour for existing firewall rules in the wild

**Comment by martinb3** [comment]
Thank you!

**Pull request merged**
