### PR TITLE
Multiple additions for iptables support

### PR DESCRIPTION
**Pull request by rdoorn**
Hello,

As per my previous pull request, the same features now for the HWRP:
- allow active iptables rules to be saved
- add ability to add log entries
- fix the order of rule parameters created (required for proper detection)
- use multiport for allowing arrays of source and destination ports
- change rule detection mechanism, to check if the entry is at the proper line number, when a position is given.
- allow for passing a raw line, this is needed to add zap support, for easy removal of line, without having to dissect it per parameter. it will also allows to complex rules which don’t fit in normal behaviour.
- Use rules name as description, when having many lines this will tell you exactly what chef rule created it

Other fixes:
- remove echo’s from the drop policy when enabling iptables
- fix detection if iptables is active
- upcase state’s required for proper matching and allow this to be an array of states

additionally the "provides" statement in the ufw provider doesn't work with chef 11.18, i can only guess that this is optional, as its not in the iptables provider. but feel free to correct me if wrong ;-)

Kind Regards,
Ronald

### CODE REVIEW

**Comment by martinb3** [comment]
Thanks @rdoorn!

Indeed, the provides syntax is chef 12 and greater. When starting my revisions, I had some feedback from Opscode that we should be using that syntax. I still need to explore the backwards-compat way for helping chef 11.x discover providers for resources.

Also, I'd still be very much interested in the firewalld support you worked on.

Thanks again!

- Martin

**Comment by martinb3** [comment]
One other thing I noticed -- `iptables -S` isn't supported by some of the distros. I'm not sure there's a nice workaround for that.

**Comment by rdoorn** [comment]
Hi @martinb3 

Thanks for accepting the pull request!
As for the iptables -S, i'll create a new pull request to use iptables-save again (i hope thats better supported with other distros too), a long as the output is the same we should be alright. in worst case we'll need multiple checks for the different distro's depending on what they support.

I'm currently converting the firewalld part to a HWRP as well, it will take me a couple of days to do and test this. But will add a additional pull request for that soon.

Kind Regards,
Ronald

**Comment by rdoorn** [comment]
Hi @martinb3 ,

Is it the plan that this cookbook will no longer support chef 11? as currently the "provide" statements mentioned earlier are back in the class, which are not supported in chef client 11.18. as well as the removal of the original way these providers were written. both things currently prevent me from testing this cookbook on a chef 11.18 client.

the backwards compatibilty is important for me as not everyone can update to chef 12 that easily..

Just need to know the way this cookbook is planning to go, before undoing these things again to get the cookbook working on my current environment.

Regards,
Ronald

**Comment by martinb3** [comment]
Hi @rdoorn,
I'd like to get chef 11 backwards compatible code here. I just started with chef 12, but if we can make a way to make it backwards compatible, that would be great too. - Martin

**Pull request merged**
