### PR TITLE
Bug fix: Fixed redirect comparision; cdre-security-centos64-65 …

### PR DESCRIPTION
**Pull request by mdwulit**
This is small change fixing comparison problem. 
I have hard time to use firewall cookbook to add following rule:
iptables -A PREROUTING -t nat -p tcp -m tcp -m multiport --dports 80 -m comment --comment "port_forwarding_80to7001" -j REDIRECT --to-ports 7001

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by martinb3** [comment]
Hi there -- would you mind signing the Chef CLA @mdwulit?

**Comment by mdwulit** [comment]
Hi. I have signed the chef ICLA agreement ...

**Comment by mdwulit** [comment]
Hi.

I have singed the ICLA agreement ... Could you please try again.

Best regards
Marek

On Wed, Jul 15, 2015 at 10:15 AM, Martin Smith <notifications@github.com>
wrote:

> Hi there -- would you mind signing the Chef CLA @mdwulit
> <https://github.com/mdwulit>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opscode-cookbooks/firewall/pull/72#issuecomment-121629534>
> .
>



-- 
Best Regards
Marek Dwulit

**Comment by martinb3** [comment]
Thank you!

**Pull request merged**
