### PR TITLE
Support protocol number

### PR DESCRIPTION
**Pull request by shoekstra**
This allows you to specify protocol number when using either the iptables or firewalld provider.

Integration tests are done, aim to add spec tests in near future.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by shoekstra** [comment]
Hello,

I've pushed this again without the updated Gemfile commit and now have the signed CLA tag.

Cheers,
Stephen

**Comment by shoekstra** [comment]
Hi,

I've rebased this PR from master, so should be good to merge now.  Please let me know if anything is still outstanding.

**Comment by martinb3** [comment]
Hi there -- are you sure this is rebase'd? I see older commits that are already in master, but with different hashes, when I'd expect to just see your one new commit. I've merged this commit of yours in https://github.com/opscode-cookbooks/firewall/commit/4fa35f4707ee7cfec670bb5947f79438a5c93073.

**Comment by shoekstra** [comment]
Hey,

Thanks for merging!  Re rebasing, I thought so, it's the first time I've done it.  I found a post that said I needed to checkout this branch and do `git rebase master`, which I did.  Thought it was weird to include the other commits in this PR.

Anyway, thanks again!

**Pull request closed without merging**
