### PR TITLE
firewalld needs to have a check to install 'firewalld' package if not installed

### PR DESCRIPTION
**Pull request by joshoohaah**

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @joshoohaah

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by martinb3** [comment]
Would you tell us what distro you're using that supports firewalld but doesn't install it by default? Also, I think I would prefer this in a recipe vs. a provider, as it's going to add the package resource to the run list, but not necessarily install it before the provider action executes (that usually causes a failure, since the package resource hasn't been run yet).

Also, please sign the Chef CLA, if you don't mind. Thanks!

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by joshoohaah** [comment]
I've signed the CLA.
i was using centos 7.   however some images that we have created/modified out there as AMI's out on amazon did not have firewalld installed. So i was looking at the iptables logic in the `provider_firewall_iptables.rb` how they handled it:
```
    def action_enable
      converge_by("install package #{package_name} and default DROP if no rules exist") do
        package package_name do
          action :install
        end
```
in there they install iptables package.
But in the `provider_firewall_firewalld.rb` the package installation is lacking:
```
class Chef
  class Provider::FirewallRuleFirewalld < Provider
    include Poise
    include Chef::Mixin::ShellOut
    include FirewallCookbook::Helpers
```

**Comment by martinb3** [comment]
Thanks! This has been merged in https://github.com/opscode-cookbooks/firewall/commit/689b558a2c521604595ccd54f655ff44b4a24d23.

**Pull request closed without merging**
